# following https://github.com/jekyll/minima
title: SPARK
author: Shiquan Sun, Jiaqiang Zhu and Xiang Zhou
email: shiquans@umich.edu jiaqiang@umich.edu xzhousph@umich.edu
description: Spatial PAttern Recognition via Kernels

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
date_format: "%b %-d, %Y"

# generate social links in footer
social_links:
github: xzhoulab
rss: rss
# dribbble: jekyll
# facebook: jekyll
# flickr:   jekyll
# instagram: jekyll
# linkedin: jekyll
# pinterest: jekyll
# youtube: jekyll
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
# youtube_channel_name: CloudCannon
# telegram: jekyll
# googleplus: +jekyll
# microdotblog: jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
- jekyll-feed
- jekyll-seo-tag
